package:
  name: coptictranslittest
  version: 0.0.1

source:
  git_rev: master
  git_url: https://github.com/shehatamichael/coptic-transliteration

extra:
  channels:
    - conda-forge

requirements:
  host:
    - python
    - pynini

  run:
    - python

test:
  imports:
    - coptictranslittest

about:
  home: https://github.com/shehatamichael/coptic-transliteration
  license: GNU GENERAL PUBLIC LICENSE
  license_file: LICENSE
  summary:
