package:
  name: coptic-translit
  version: 0.1

source:
  git_rev: master
  git_url: https://github.com/shehatamichael/coptic-transliteration

requirements:
  host:
    - python

  run:
    - python

test:
  imports:
    - coptic-translit

about:
  home: https://github.com/shehatamichael/coptic-transliteration
  license: GNU GENERAL PUBLIC LICENSE
  license_file: LICENSE
  summary:
