package:
  name: coptic-translit
  version: 0.1

source:
  fn: coptic-translit-0.1.tar.gz
  git_rev:
  git_url:

build: 
  number: 0
requirements:
  host:
    - python
    - pynini

  run:
    - python

test:
  imports:
    - coptic-translit

about:
  home:
  license:
  summary:
